% readFile.m --version 1.0
% created on 03/19/2019, by wangnan

%First run this script to generate data from weight.txt file
%only for mobileNetV2
%if you want to read mask or masked_weight, please modify outputfilename as
%in readData_lgc.m
%you can modify sourceFileName and outFileName according to your network
%structure
sourceFileName = 'lgc_mask_withoutGrouplasso_at_epoch_66.txt';
disp(sourceFileName)
%weight
outFileName = {'block_0101_expand.txt', 'block_0101_project.txt', ...
               'block_0201_expand.txt', 'block_0201_project.txt', ...
               'block_0202_expand.txt', 'block_0202_project.txt', ...
               'block_0301_expand.txt', 'block_0301_project.txt', ...
               'block_0302_expand.txt', 'block_0302_project.txt', ...
               'block_0303_expand.txt', 'block_0303_project.txt', ...
               'block_0401_expand.txt', 'block_0401_project.txt', ...
               'block_0402_expand.txt', 'block_0402_project.txt', ...
               'block_0403_expand.txt', 'block_0403_project.txt', ...
               'block_0404_expand.txt', 'block_0404_project.txt', ...
               'block_0501_expand.txt', 'block_0501_project.txt', ...
               'block_0502_expand.txt', 'block_0502_project.txt', ...
               'block_0503_expand.txt', 'block_0503_project.txt', ...
               'block_0601_expand.txt', 'block_0601_project.txt', ...
               'block_0602_expand.txt', 'block_0602_project.txt', ...
               'block_0603_expand.txt', 'block_0603_project.txt', ...
               'block_0701_expand.txt', 'block_0701_project.txt'};
%mask
outFileName_2 = {'block_0101_expand_mask.txt', 'block_0101_project_mask.txt', ...
               'block_0201_expand_mask.txt', 'block_0201_project_mask.txt', ...
               'block_0202_expand_mask.txt', 'block_0202_project_mask.txt', ...
               'block_0301_expand_mask.txt', 'block_0301_project_mask.txt', ...
               'block_0302_expand_mask.txt', 'block_0302_project_mask.txt', ...
               'block_0303_expand_mask.txt', 'block_0303_project_mask.txt', ...
               'block_0401_expand_mask.txt', 'block_0401_project_mask.txt', ...
               'block_0402_expand_mask.txt', 'block_0402_project_mask.txt', ...
               'block_0403_expand_mask.txt', 'block_0403_project_mask.txt', ...
               'block_0404_expand_mask.txt', 'block_0404_project_mask.txt', ...
               'block_0501_expand_mask.txt', 'block_0501_project_mask.txt', ...
               'block_0502_expand_mask.txt', 'block_0502_project_mask.txt', ...
               'block_0503_expand_mask.txt', 'block_0503_project_mask.txt', ...
               'block_0601_expand_mask.txt', 'block_0601_project_mask.txt', ...
               'block_0602_expand_mask.txt', 'block_0602_project_mask.txt', ...
               'block_0603_expand_mask.txt', 'block_0603_project_mask.txt', ...
               'block_0701_expand_mask.txt', 'block_0701_project_mask.txt'};


fid = fopen(sourceFileName,'r'); %open your source file
line = '';
if contains(sourceFileName, 'mask')
    outFileName = outFileName_2;
end

len = length(outFileName);
for i=1:len
    line = fgetl(fid);
    outfile = fopen(outFileName{i},'w');
    while ~contains(line, 'New')
        temp = str2num(line);
        fprintf(outfile,'%7.4f\t',temp); %write data to outfile
        fprintf(outfile,'\n'); %Wrap
        line = fgetl(fid);
        if contains(line, 'New') %skip when read 'New ...'
            continue;
        end
    end
    fclose(outfile);
end
fclose(fid);
fclose all;


